### ISSUE TITLE
Add emplexer to main screen

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#11]
Hi newloran2

I know there are some things  you can't do, due to the limitations of Dune, but is it possible to include  an option for emplexer to be added to the start up screen(source)?
![screenshot1](https://f.cloud.github.com/assets/2873112/63048/ef85a1c8-5dac-11e2-9ca0-2d1b67670186.jpg)

**Comment by newloran2** [comment]
Good idea ):.
I like this to, but I don't know if this is possible, but I try.

Em 13/01/2013, às 16:13, 20mxm notifications@github.com escreveu:

**Comment by newloran2** [comment]
emplexer is configurable to added at main screen  :).

![screenshot26](https://f.cloud.github.com/assets/1266496/110901/867b7cf2-6adb-11e2-99ab-7fdc32eb1d0a.png)
