### ISSUE TITLE
Resume play and TV info

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#13]
Hi newloran2

Resume play works independently of each other, Depending on how you start playing files.
I've tried to make it clear as possible.

eg:
(A settings) stopped at 5min 
(B settings) stopped at 1min

 If I play A setting in B setting emplexer will start a 1min

*A settings
pressing info then play works fine

![1](https://f.cloud.github.com/assets/2873112/74494/554fbb94-6094-11e2-92e5-417619354d00.jpeg)

press info again, episode and name shows.

![2](https://f.cloud.github.com/assets/2873112/74495/58bae358-6094-11e2-9c1a-5b881d7b2c7c.jpeg)

*B settings
Pressing play works fine

![3](https://f.cloud.github.com/assets/2873112/74496/5c324d82-6094-11e2-87f6-e08a197f3807.jpeg)

No episode number or title info

![4](https://f.cloud.github.com/assets/2873112/74497/61780e94-6094-11e2-823c-db6d0460f30a.jpeg)

**Comment by newloran2** [comment]
dupe
