### ISSUE TITLE
Specific Filter

### ISSUE THREAD

**Issue by cgechter** [newloran2/emplexer#17]
I have a Dune Smart B1 and I set up Emplexer and it works good, I can view all of my Movies, check their info, and play them. However when I select a specific filter when "Movies" is highlighted and I make any selection, like Content rating, unwatched, genre, etc I get a screen which states "empty". 

If I selct Content rating it gives me the option to choose, "G", "PG", "PG-13", "R", and then when I select any of them it shows "empty". This works on other Plex apps I have, like for the LG TV.

**Comment by kungktd** [comment]
Same here. If I chose Unwatched for movies I don't see any movies, just a screen saying empty.
If I select Unwatched for Tv shows it works fine though.

**Comment by newloran2** [comment]
Now all filter work.
