### ISSUE TITLE
TV Episodes info

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#2]
Hi newloran2

Can you please add episode information for Tv series & films, in your next update.
with a nice GUI, similar to plex  or your own design?

Thanks
20mxm

**Comment by newloran2** [comment]
now episode/film info work.
Tv show/Movie info is ativated with info button on remote.

![screenshot23](https://f.cloud.github.com/assets/1266496/49905/0b69cad2-5983-11e2-9f4b-f10c3c2fc58f.png)

**Comment by Blurayx** [comment]
Wow, That looks really Good!!!! 

Thank you \0/
