### ISSUE TITLE
Subtitles options

### ISSUE THREAD

**Issue by mbnn** [newloran2/emplexer#21]
If possible it would be awesome if we could get an option to select what subtitle to play (maybe through NFS?) and a way to increase/decrease subtitle offset when it's not 100% in sync with the audio.

**Comment by noipapoti** [comment]
I definitely second this one.

Now I make sure pretty much all my media are in MKV container and I mux in the required subtitles while setting the proper language and making the preferred subtitle the default (using MKVToolNix on a Mac). It is a bit of a long way round to get the Dune with Emplexer to provide the proper subtitles.

**Comment by newloran2** [comment]
guys try to use Dune Playback instead  vod playback, in this mode all features supported by dune are enabled.

**Comment by noipapoti** [comment]
Newloran2,

Attached a tarball with exmaples of complex filenames. I hope these come
over properly.

Regards,
noipapoti

**Comment by newloran2** [comment]
noipapoti,
Not receive attachments in email response on github, if possible please post them somewhere as paste.bin or even here in the response body.

**Comment by noipapoti** [comment]
Do you have a mail address I can send it to? The tarball is small (about
20K) as I only included an empty MKV file and a related .srt file.

**Comment by newloran2** [comment]
send to newloran2@gmail.com

**Comment by newloran2** [comment]
As this bug is related to vod playback, i'll close it because this mode is no longer present in emplexer 2.0.
