### ISSUE TITLE
Plex icon as app icon

### ISSUE THREAD

**Issue by mbnn** [newloran2/emplexer#22]
Would it be possible to change the dune icon to a plex icon for the emplexer app?

**Comment by newloran2** [comment]
Use plex icon is not possible, this icon is a register mark.
I'm accept any emplexer icon submition :).

**Comment by mbnn** [comment]
What are the exact size and format you can use? (pixels and png/jpg/gif)?

**Comment by mbnn** [comment]
You may use the plex icon by the way, other plex apps made by the community also use the main plex icon ;) Like plex for appletv.

**Comment by newloran2** [comment]
All this apps that use plex icon is made by plex team.

**Comment by mbnn** [comment]
No it's not the APPLETV app is not made by the plex team ;)

**Comment by mbnn** [comment]
What do you think of this icon? :) Let me know if you need diff size.

![emplexer](https://f.cloud.github.com/assets/1856746/110790/d71e2a94-6ad4-11e2-98d2-e11a04d83e35.png)

**Comment by mbnn** [comment]
I hope this works: the .aai file for dune.
http://gameconnect.net/temp/emplexer.aai

**Comment by newloran2** [comment]
Wow nice icon :).
I added this icon to emplexer, and now is possible to add emplexer to main screen (with a nice icon :)).
![screenshot26](https://f.cloud.github.com/assets/1266496/110896/33a55c6e-6adb-11e2-8508-97e36fd7b872.png)
