### ISSUE TITLE
NFS: Plex server (Server) and separate storage (NAS)

### ISSUE THREAD

**Issue by mbnn** [newloran2/emplexer#24]
For the NFS option please add a way so that when someone has a NAS with the media on it they can add that while plex server is on another server.

**Comment by newloran2** [comment]
Now on setup when select smb or nfs on connection type a modal appears.
On this modal you setup your paths to correct server.
![screenshot28](https://f.cloud.github.com/assets/1266496/120930/65643846-6d52-11e2-8fdd-7f205df429a7.png)
![screenshot27](https://f.cloud.github.com/assets/1266496/120931/6586ad0e-6d52-11e2-80cc-b40cf399dc47.png)
