### ISSUE TITLE
Red & Green remote short cuts

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#31]
The Red & Green short cuts on the remote are disabled, for Audio sync & Pal sound speed correction.
Currently Pal sound speed correction can not be turned on with emplexer.
If it's not possible to enable the short cuts on the remote, can you fix the on/off  Pal sound speed function
![1](https://f.cloud.github.com/assets/2873112/175640/e13d09da-7b52-11e2-8b26-6677a170014a.jpg)

**Comment by newloran2** [comment]
currently is not possible to add any shortcut on remote, but this feature is enabled on menu (pop up button on remote).
![screenshot34](https://f.cloud.github.com/assets/1266496/179821/4dc4412c-7c11-11e2-9e94-9cd6fcaf6cd1.png)

**Comment by Blurayx** [comment]
BUG
Highlighted  in the first post ,emplexer currently disables the ability to turn it on
