### ISSUE TITLE
no empexer.log created

### ISSUE THREAD

**Issue by malinwa001** [newloran2/emplexer#35]
after configuring my nas (ds713+) an my dune D1 i was able to play the video and movies from my nas but no covers or log files where downloaded or created. Movie info was was available. Where did i go wrong?

**Comment by newloran2** [comment]
Do you have a system storage?
Your system storge have space?

To emplexer create the logs attach a had disk, usb drive or memory card to dune, create on root of this drive a folder named dune_plugin_logs and reestart your Dune, now use your emplexer and emplexer.log will be created on dune_plugin_logs/emplexer/emplexer.log

**Comment by newloran2** [comment]
Do you have a system storage (not flash storage)?
Your system storage have space?

To able emplexer to create logs attach a usb stick, memory drive or hard disk in your Dune, on top of this drive create a folder named dune_plugin_logs.
Restart your Dune and use again the emplexer, now emplexer.log will be created on dune_plugin_logs/emplexer/emplexer.log.

Plz send-me this log.

To temporarily avoid this bug, go to setup->applications->emplexer->Use cache and mark with no, this make page load more slow but show all images.

Thank's

**Comment by malinwa001** [comment]
thanks for the quick response! Whife is using the tv now so testing is for later.

my system has a nas with 3TB space, 2 TB available.
no HD or stick is attached to the dune, i'll test it with a SD card.

**Comment by malinwa001** [comment]
moved the log to my dropbox : https://www.dropbox.com/s/nnukdrnd2u00mrr/emplexer.log

**Comment by newloran2** [comment]
I See in your log file the problem.

You don't have any system storage.

To resolve image problem, remove emplexer, install a system storage and and reinstall emplexer.

**Comment by malinwa001** [comment]
i'll try that. Is a SD-card a sollution as system storage?

**Comment by newloran2** [comment]
Yes, but you need to activate http://dune-hd.com/firmware/usb_flash_drive/.
