### ISSUE TITLE
main folder "movies" not working

### ISSUE THREAD

**Issue by zagon** [newloran2/emplexer#4]
great work and great project!!!
when I configure the emplexer, I see my library name...."movies", but when I try to enter, I get the message "error when obtaining xml of plex".. I can use plex on my ipag, so I know the server run fine...

how can I debug? any log?
thank you!

**Comment by zagon** [comment]
hi there after a few hours surfing, I see that the plex server need high perfs for transcoding....
in the case of duneHD, I guess transcoding is not needed..  According to you, is there a way to setup the server and client plex to not trancode and let the dune play the movies?
(I am using a synologu dS212 nas, and the plex server seems not powerfull enough to transcode....

thank you

**Comment by zagon** [comment]
okay.. coming back with details....
I still have the same issue selectioning the "movies" main folder (no xml) but playing arround, I found out the the only working filter is "recently released".. all the other filters give the missing xml message...., when I use the recently release filter, everything works fine.....

**Comment by newloran2** [comment]
Zagon, thanks for your reply.

emplexer create a folder named dune_plugin_logs on top of your internal storage (if you don't have internal storage add an usb stick or sd card), i need the all logs on this folder.

Please send-me this logs.

PS: emplexer for now only work with direct play, if you need activate transcode on PMS this is a bug.
PS2: my plex is in DS712 and i don't have power to transcode session to.

**Comment by newloran2** [comment]
Zagon,

you need an usb stick that is not an system storage.

format this usb stick in ntfs or fat32 (or ext3 if you use linux) and plug this on dune.

now simulate the bug and on dune navigate on root of your usb stick, dune_plugin_logs created and populate with few logs.

these are logs that i need.

okay.. then I know you are looking for the same as I am: use plex as media 
center that scraps ans publishes the movies, but no transoding... 
what I can't understand is why the the plex pluging crashing when I try to 
play an mkv, as my dune can play very easily accessing the files on the 
nas.... 
I was expecting the pluging to only send to the client the path of the file 
to play and that's it, but it seems it does more... 

I get my usb stick from dune... but when connecting it to my laptop it says 
it is not formated....

**Comment by zagon** [comment]
will do!

**Comment by zagon** [comment]
damned,
I only get an empty fifo.txt file....

**Comment by zagon** [comment]
this is very weird.
which version of your firmware?
the folder dune_plugin_logs has create by emplexer? if yes plese shutdown your Dune and try again.

the weird thing is that the movies folders does not work, but the tv shows
does...
in the tv shows, I even have some videos that are working.. but only 10%
of them...

even the ones that works, I get a "could not find server" message; although
the movie starts after some seconds....

**Comment by Blurayx** [comment]
Are you using a firewall or antivirus software?

Also there is a known issue with emplexer, That If the movie info has commas . you can not access your files.
The only quick fix at the moment is to delete all movie info and replace it with the name of the movie.

**Comment by zagon** [comment]
nope, nothing run on the synology..
only plex and download station

**Comment by zagon** [comment]
I can arrange an account to connect to my syno if needed

**Comment by newloran2** [comment]
Zagon, please, try reboot your dune with a folder named dune_plugin_logs created on top of your USB stick created.
After this emplexer problaby make all useful logs on that.
With this logs is much more easy to determine what's the problem.

**Comment by zagon** [comment]
will do! but as the dune created the folder aleeady, i guess it foud the
usb stick

On 19 déc. 2012, at 23:30, newloran2 notifications@github.com wrote:

Zagon, please, try reboot your dune with a folder named dune_plugin_logs
created on top of your USB stick created.
After this emplexer problaby make all useful logs on that.
With this logs is much more easy to determine what's the problem.

—
Reply to this email directly or view it on
GitHubhttps://github.com/newloran2/emplexer/issues/4#issuecomment-11551852.

**Comment by zagon** [comment]
hi, I manage to fill the log file...
here is the file

**Comment by newloran2** [comment]
this bug is done, please test the new version and if this not work i'll reopenen this bug.

**Comment by zagon** [comment]
thank you..
I will test and come back to you

**Comment by zagon** [comment]
hi, indeed the bug is not there anymore:
I can see all movies!...

unfortunately I get "format not supported" on a lot of them... although my
dune can play all the files if not using plex....

any idea why?

**Comment by newloran2** [comment]
zagon,

simulate this error and send-me your emplexer log.

**Comment by zagon** [comment]
i would but i think the issue is at the plex server side ( none of my plex
client are able to play(iphone or ipad)

On 8 janv. 2013, at 21:10, newloran2 notifications@github.com wrote:

zagon,

simulate this error and send-me your emplexer log.

—
Reply to this email directly or view it on
GitHubhttps://github.com/newloran2/emplexer/issues/4#issuecomment-12014858.

**Comment by newloran2** [comment]
zagon,

try plex reboot, the last 3 releases have caught me with some frequency with me.

if you able to play your medias on other clients but in emplexer no i analize better what's the problem.

**Comment by zagon** [comment]
hi !

now my plex server is working fine (I downloaded a movie for I pad and was
able to play it on my ipad through plex.....

unfortunately, when I use my dune with the emplexer I always get the
invalid format error... eventhough I can play the files with my dune if I
access the nas directly....

thanls for helping

**Comment by newloran2** [comment]
Zagon, 

plz send-me your employer.log and employer.log.old and i see what's the problem.

Em 12/01/2013, às 12:35, zagon notifications@github.com escreveu:

> hi ! 
> 
> now my plex server is working fine (I downloaded a movie for I pad and was 
> able to play it on my ipad through plex..... 
> 
> unfortunately, when I use my dune with the emplexer I always get the 
> invalid format error... eventhough I can play the files with my dune if I 
> access the nas directly.... 
> 
> thanls for helping 
>

**Comment by zagon** [comment]
hi,
here you are (that's all I find)
