### ISSUE TITLE
Selection box misalignment

### ISSUE THREAD

**Issue by shotfirer** [newloran2/emplexer#40]
There is a small bug in the latest version (from March, 18) - selection box in TV episodes is a bit off (shifted down), so it crosses episode title.
![screenshot2](https://f.cloud.github.com/assets/3914616/278303/7fbddd2e-90e2-11e2-83ec-0692b442c69b.png)
In previous version everything was ok. I've tried to turn cache on/off - doesn't change anything.

**Comment by newloran2** [comment]
Sorry for this bug, the fix was submitted.
