### ISSUE TITLE
Non-latin text encoding in playback info is garbled

### ISSUE THREAD

**Issue by shotfirer** [newloran2/emplexer#41]
There is some kind of problem with non-latin (cyrillic in my case) movie descriptions.
Big info screen looks fine
![screenshot4](https://f.cloud.github.com/assets/3914616/279534/d907b806-912c-11e2-84b2-dfc74e476fe8.png)
But in playback info banner all text, except movie title, is garbled (wrong encoding i think)
![screenshot3](https://f.cloud.github.com/assets/3914616/279542/6acb96d6-912d-11e2-91da-b4c3dde03c1f.png)
I'm playing everything over NFS, so maybe it's a Dune problem, not an emplexer's?

**Comment by newloran2** [comment]
you can please post here the description?

**Comment by shotfirer** [comment]
Yeah, sure. Here it is:

Романенко с Лобановым спрятали в больнице шины от джипа. У Фила пациентка с Кавказа — американцу пришлось столкнуться и с ее «горячими» братьями. Кисегач хочет познакомить Быкова со своей мамой. Взамен на хорошее поведение обещает подарить ему мотоцикл. Быков ходит как шелковый. Но Кисегач обещание выполнять не хочет.

And, just in case, link to this episode of TVDb
http://thetvdb.com/?tab=episode&seriesid=154431&seasonid=491572&id=4315483&lid=22
