### ISSUE TITLE
Remaining Time

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#5]
Can you please add Seconds with Remaining Time

**Comment by newloran2** [comment]
20mxm, plese explan this bug.

**Comment by Blurayx** [comment]
When you press info on the remote, to see how much time is remaining for Movies or TV shows, it only shows minutes.

**Comment by newloran2** [comment]
20mxm,

I don't have access to this thing and for now this is imposible to do.
If HDI make possible to control OSD i reopen this bug.
