### ISSUE TITLE
Album Artwork

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#55]
Album Artwork support if possible.

Thanks

**Comment by noipapoti** [comment]
Newloran2 has commented on this in another thread, noting it is on the TODO list. See https://github.com/newloran2/emplexer/issues/57#issuecomment-20570171.

I would love to see this as well. Before emplexer could play music it showed artwork (although not very nice using some dune defaults), but that was not very useful without being able to play the music.

I find the current behavior of emplexer for playing music (needing the play button on a album) not ideal when compared to the default music browser of the dune when you can use enter on a single track, but still play the whole album. But for now, I'm very happy that it works already.

**Comment by newloran2** [comment]
Hello 20mxm and  noipapoti,

Artwork in album and in the other sections are now possible  with templates.
I'll post soon a tutorial about how to use templates to customize the emplexer.

That feature only present at 2.0 branch.
