### ISSUE TITLE
Resume Play issues 

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#59]
With the current version resume play, will start about 2 or 3 minutes into a new TV or movie file,with ASK Resume play enabled.

This issue does not happen with all files

**Comment by noipapoti** [comment]
Noticed same behavior.

An example sequence may help track the bug:
- play a series episode
- move ahead in time and stop
- play any following episode (not played before, although not sure if this matters)
- play will start at time of stopping previous episode

Leaving Emplexer (go to Dune main screen) and going back into Emplexer allows you to start the episodes from the beginning again.

There is one really annoying part of this bug. If the next episode is shorter than the time you stopped the previous one you cannot play it as it immediately tries to go past the end of the episode. And there is no way to go to another time as the playing never actually starts... (Leaving Emplexer and starting it again is a workaround for this bug).

**Comment by newloran2** [comment]
Fixed in the last release.
