### ISSUE TITLE
Unable to open emplexer directly - Getting an XML 404 error

### ISSUE THREAD

**Issue by kris-anderson** [newloran2/emplexer#60]
I'm not sure of the exact cause of this issue since I recently:

1.) Switched to a new Ubuntu Server to run Plex (migrated from a previous Ubuntu Server)
2.) Upgraded my Dune B1 Firmware (latest stable... happened about 2-3 weeks ago)
3.) Updated Emplexer to the latest version

I have two libraries in Plex. TV and Movies. I can click on TV from within Emplexer and all my episodes show correctly. If I click on Movies though, I get an error that pops up and says:

"the area you are trying to access does not return any xml (404)"

If I open up the menu options over Movies and chose something like Year, and then open up 2013, all my movies for that year show correctly. I'm able to navigate through my collection that way, but clicking on emplexer directly (which used to show me all my movies) no longer works.

I've re-installed emplexer a few times and that didn't fix anything. I've also cleared the system and flash storage on the Dune. I've verified the settings in emplexer are correct for my Plex Server.

On the Plex side of things I've forced a deep scan, ran an optimization, and emptied the trash. The web interface shows all my movies, but emplexer is still not working correctly.

**Comment by noipapoti** [comment]
I have seen these errors and this behavior as well. And also errors giving me a "format not supported".

In my case it had to do with file and/or directory names with complex characters in it. Plex can handle that, but it seems emplexer and/or the Dune firmware stumbles on these. (I've also had the AFP deamon in Linux crash on these when renaming from my Mac). Simplyfying the file and/or directory names might help. Don't forget to rescan afterwards in Plex and empty the Trash in Plex.

**Comment by kris-anderson** [comment]
That makes sense. I know of at least 1 movie in my collection that contains some non standard characters (that was added recently). I see that Plex convers those characters into, I believe, unicode. Hopefully Emplexer can be updated to convert those characters on the fly so I don't have to change my media from their correct names just for Emplexer.

**Comment by newloran2** [comment]
Guys sorry for this late response.

kris-anderson:
Try to disable cache, i will provide a solution to this issue.

noipapoti:
You can please send-me some examples of complex names?

**Comment by kris-anderson** [comment]
Thanks for the reply newloran2. I tried to disable the cache, but that still causes the issue for me.

I'm not sure if this is the exact movie that's causing issues for me... but the path that Plex is using for the media is:

/mnt/nas/Movies/REC 3 Genesis (2012)/[REC]%C2%B3 G%C3%A9nesis (2012).mkv

Here is what the actual file name looks like:

![characters](https://f.cloud.github.com/assets/1562427/939760/8e422468-011c-11e3-997d-a55f5a458179.jpg)

I'm attaching that as an image because Github will likely convert those into something else if I paste them.

Note that I can't play that movie using Emplexer (I get an error). If I load the movie by navigating to it over SMB through the Dune though, it does play.

**Comment by cindernat** [comment]
Hi newloran2,
Many thanks for your time and effort put into this app. I got the app working on my Dune all except for movies folder, in which I get the XML 404 error. Doesn't matter which pop-up option I select, I get the same error: 'the area you are trying to access does not return any xml (404)'. Anything else I can try please?

As mentioned, TV, music & photos work fine.

**Comment by newloran2** [comment]
Hello  cindernat,

if possible simulate that error and send-me your emplexer log and i try to help you.

**Comment by cindernat** [comment]
Yes was just about to do that for you. I did a few other things as well (checked photos, though I can browse folders they all show as empty).

What is the best way to send you the log file as in this window I can only upload an image.

**Comment by newloran2** [comment]
You can send  to my email newloran2@gmail.com.

About photos and other sections, i'll fix on 2.0 https://github.com/newloran2/emplexer/tree/2.0

**Comment by newloran2** [comment]
hey guis please try with the b03 version and if have any of these bug fell free to reopen that issue.
https://github.com/newloran2/emplexer/releases
