### ISSUE TITLE
Auto play next episode

### ISSUE THREAD

**Issue by noipapoti** [newloran2/emplexer#61]
At the moment Emplexer does not automatically play the next episode when watching a series. Often this is fine when you have long episodes, but for series with short episodes (e.g. 5 min for cartoons and children series) it is nice if emplexer would automatically play the next episode.

Some possible ways to solve this include:
- allow it to be turned on via e menu if when playing an episode
- allow it to be set in the settings (never play next episode, always play next episode, only play next episode if shorter than xx minutes)
- Enter on episode - play one; play button on episode, automaticalle play next episode

Not sure what is feasible, but it helps to keep our youngest family member happy once in a while...

**Comment by Blurayx** [comment]
I opened Auto play feature issue 6 months ago

https://github.com/newloran2/emplexer/issues/32

**Comment by newloran2** [comment]
noipapoti i will attach your suggestions to the original bug.
