### ISSUE TITLE
 subtitles doesn't work at all

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#7]
Quote from Zodler Plex forum

"Thank you so much for this. This is a very important tool for Dune players. I tried it and it works great with resume positions and stuff. 

However, there is only one major thing missing, Subtitles. I tried with srt/txt subs inside MKV and outside MKV and this Dune client can not read/show subtitles.

Could you please add subtitle support? Subtitle is very important and unfortunately without subtitle support I can not use this Plex Dune app"

**Comment by newloran2** [comment]
unfortunately this is not a bug, this is a limiation on dune api expecialy on vod playback.
for now I cannot make nothing.

with this limitation  i don't have access to subtitles config/enable/etc.

To enable subtitle on emplexer go to _Setup->Playback->Subtitles->Enable subtitles by default for file._ and enable it.

This is a terrible workaround while HDI don't enable subtitle config on vod playback.
