### ISSUE TITLE
houve un problema ao acessar essa area, try again (401)

### ISSUE THREAD

**Issue by Djuna** [newloran2/emplexer#78]
Hello, 

I installed Emplexer on my Dune TV-102, seemingly without a hitch, however when I try to open the app I get the following error message:

houve un problema ao acessar essa area, try again (401)

Things I've tried....

Changing connection type to smb and nfs. I get the same error message when I try to change this setting. 

Checked my Plex IP and port (the default) a million times. I'm viewing my Plex database simultaneously on my laptop's web client, at the same address. All is working fine. 

Rebooted my Dune. 

Checked my access to media via Sources... Network Browser... Multimedia Devices... Plex Media Server: (Computer Name). I can see and play videos here, but, of course, the browsing interface leaves much to be desired. 

Checked my system storage (which I set up specifically for this exercise). It's attached. 

Checked my ability to make an http connection via the web browser. All good!

Any ideas??

Many thanks! This looks like a great development and I'd very much look forward to getting it going. 

Best!
Djuna

**Comment by newloran2** [comment]
Hello Djuna,

You are trying to access a remote plex?
If so, that is the problem, emplexer for now doesn't have support for remote plex (myplex).

Please send-me your emplexer.log and i can help you better.

**Comment by Djuna** [comment]
Thanks for your speedy reply :) 

I'm trying to access my PMS on a wired local network. 

I see now that the 401 error seems similar to what I get when I try to go to http://(Plex IP):32400 from a computer on the same network: "401 unauthorized". I am also a unable to connect to myPlex via the web interface. My ISP puts me behind a NAT which may be my bigger problem.  

I just spent several hours disconnecting  my Asus RT AC68U router from my modem and setting it up as a dedicated media bridge between my PST computer and my Dune (both wired). I thought for sure that would solve my problems, but I still wasn't authorized to view http://(Plex IP):32400 on that same computer, or connect to myPlex. Browsing the Plex web client worked fine, however. 

It's not expensive to get a static IP via my ISP, which should get me out from behind NAT, but given today's experiments, I'm not fully confident that would help. 

This may extend beyond the call of duty for emplexer, but any pointers would be most welcome! 

Are emplexer logs stored on the storage device attached to my Dune? And is it OK to just yank that out? I don't see any eject function... 

Thanks again! 
Djuna

-------- Original message --------

**Comment by Djuna** [comment]
I'm in!

I made several tweaks:

1) In my struggles to connect to myPlex, I'd clicked the "Require authentication on local networks" option under advanced settings. I think this led to my 401 error. That box should be unclicked if you want emplexer to access PMS. 

2) I signed up for a static public IP via my ISP. Then discovered that this still uses NAT and that I still couldn't connect to myPlex. Doh!

3) I set up my modem as a bridge and set up my Asus router for a PPPoe internet connection and entered my account details. (I now wonder if this would have gotten me around the double-NAT issue without the static IP.)

4) I kept the port forward I'd set up on the Asus (32400), and used the manual myPlex connection setting for port 32400. 

I could then connect to myPlex, I got xml at http://(Plex IP):32400 (not "Unauthorized), and (yoohoo!) emplexer could access my PMS.

It's real nice in there!! Thanks so much :)

**Comment by newloran2** [comment]
Hey Djuna, I am very glad that managed to solve this problem, it has shown me more problems to solve in version 2.0.

Enjoy the emplexer right there and please, any problem or suggestion feel free to ask or suggest.

If you want, take a look at the version 2.0 https://github.com/newloran2/emplexer/blob/2.0/dune_plugin_emplexer2.zip?raw=true.
I am focusing all efforts in that version. For now it is only in draft but soon will get all the features of the current version.
