### ISSUE TITLE
the area that you are trying to access does not return any xml (404)

### ISSUE THREAD

**Issue by Djuna** [newloran2/emplexer#79]
Hi there!

I'm a happy new user for emplexer, stumped about how to get the app to see some updates I've made to my PMS folders. 

Since first accessing PMS via emplexer, I modified my library a bit. I deleted one top-level section and added two new ones. In emplexer I see all the properly updated section titles, but when I click either of the two new sections I get the error:

the area that you are trying to access does not return any xml (404)

My Android app sees the updates OK, which helps me believe they exist!

I also see the same problem on one of my TV show folders. I wasn't aware that this was a new folder, but I'm now guessing that PMS replaced my folder name with a name it picked up online.  

I've rebooted both server and Dune box, and performed deep scans (in PMS) on the offending folders. No luck, I'm afraid. 

Any thoughts??

Djuna

**Comment by Djuna** [comment]
Workaround!

I just installed emplexer 2.0. It found my recently updated sections as well as a new one I created for testing purposes after the install. Yay!

What I'm most missing in the new version are the titles, but I assume these are coming soon.  

Best!
Djuna

**Comment by newloran2** [comment]
Hey Djuna,

That 404 error happen on 1.0 because you have some  title on the area you try to access that have a orphan thumbnail, check on plexweb and re-add that thumbnail.
