### ISSUE TITLE
Saving settings on branch 2.0

### ISSUE THREAD

**Issue by lorddaren** [newloran2/emplexer#80]
When I package up the emplexer.zip and deploy it on the Dune I am unable to save the configuration and launch the plugin.

**Comment by newloran2** [comment]
dlord781, 

I don't know if i understand, but i try to help. 
You tried to pack the v1 or v2?
for v1 you can download the pre-made package https://github.com/newloran2/emplexer/blob/master/dune_plugin_emplexer.zip?raw=true
to version 2 you can clone, enter in the folder and run that command zip -r dune_plugin_emplexer2.zip  *.

To both versions and any dune plugin, you can create a folder / of your hdd/flash drive named dune_plugins and create a folder with the plugin name on that and put all plugin file on that folder.

EX:
emplexer v2 is named emplexer2 (check the plugin name in the file dune_plugin.xml, any dune plugin have that file).
In my case i have a internal hdd named dune303d and the path to my emplexer2 instalation are dune303d/dune_plugins/emplexer2.

Plese if that help-you close that issue, if not tell me and i try again.

**Comment by newloran2** [comment]
:), sorry i did not see the title.
On 2,0 branch i don't have any setting yet.

**Comment by lorddaren** [comment]
Yeah the 2.0 branch.  I was running the `make pack` command. The zip deployed the plugin successfully. So is there any way to set the settings? I would like to try out the plex client stuff you got added.

**Comment by newloran2** [comment]
dlord781, 

The emplexer v2 do the self register as player automatically when you open the plugin.
For now i have a bug with android client, this client do not see emplexer as player, i'll fix that on the next release.

**Comment by lorddaren** [comment]
newloran2: Okay I would like to give it a shot but am still unable to get it deployed.  I have tried the dune_plugins folder (I have a 1TB drive with 3 partitions), but it still does not work. Any suggestions?  When I deploy it as a zip file I cannot get the settings to save after the pop up. Is there a settings file I can embed my plex server IP before I deploy the zip?

**Comment by newloran2** [comment]
Now i undestand your problem.

For now, you cannot alter your plex ip.
Try to remove completely the emplexer 2, go to setup->misc->applications->emplexer2, that will remove emplexer2 and any assets.
After that, reinstall again and the initial popup will show up.

In the next release i'll add the setup screen.

**Comment by newloran2** [comment]
dlord781, on b03 i added a setup screen with Plex ip/port setup.
