### ISSUE TITLE
PHP plugin error

### ISSUE THREAD

**Issue by kangaroo72** [newloran2/emplexer#82]
Hi there ...

I've used emplexer V1 until yesterday running fine.
After installing emplexer 2.0-B02 on my Dune 303D it says
"System error Unhandled PHP plugin error. Call the PHP plugin vendor."
Is it a known problem?

Thanks

**Comment by newloran2** [comment]
kangaroo72,

Sorry for this delayed response.
I will release a new version soon and you will able to test emplexer v2.

**Comment by kangaroo72** [comment]
Thanks

**Comment by newloran2** [comment]
b03 are ok now, if possible test with that new version.

**Comment by Blurayx** [comment]
Now working ok

Thank you

**Comment by lorddaren** [comment]
I am now getting this error with the latest version. Is there a workaround for it?

**Comment by newloran2** [comment]
Sorry, i committed a broken code, i will fix that.

**Comment by lorddaren** [comment]
Thanks. I will watch the commits.
