### ISSUE TITLE
Downloads and installs fine, can't start.

### ISSUE THREAD

**Issue by avluis** [newloran2/emplexer#83]
Got a Dune TV303D, with latest fw. I've got and internal 500gb hdd and an 8gb thumb drive as ext3 for system storage. App installs with no issue, but can't start it.
Anything you need me to try next?

**Comment by newloran2** [comment]
Hello avluis,

Wich version you try to use?
After you try to open the app show any error?
send-me your logs please.

**Comment by avluis** [comment]
Got it right here from Github, according to the Readme.md
There were no actual errors on screen, just app could not be launched.

I'm very new to Dune and not too sure how to pull the logs out.
I'm good with Linux though, so once I research that I can send them your
way.

Edit: Re-read guide, I will look for that log file for your app!

**Comment by avluis** [comment]
OK, re-formatted storage and changed skin to be the one in tutorial. I got it to start but my library is big and it gives me error: Operation time exceeded.
Any tips?

Edit:
Plex was overloaded somehow, it's all working now.

**Comment by kangaroo72** [comment]
Avluis, are you using V1 or V2?

**Comment by avluis** [comment]
Where would I find v1 or v2? Are you referring to this app or Plex or the dune tv303d?

**Comment by kangaroo72** [comment]
Hi Avluis,
this is V2 https://github.com/newloran2/emplexer/blob/2.0/dune_plugin_emplexer2.zip
But regarding your post, I believe you're using V1 ...
I refer to the app for the Dune TV303d (latest firmware)
Greetings,

Tom

PS: Starting V2 - I get a php-error - can you confirm?

**Comment by newloran2** [comment]
Avilus the emplexer logs are located on your internal hdd in the folder dune_plugin_logs.
If you don't have one folder with that name create one and all plugins logs will be stay o that folder.
Please try that version https://github.com/newloran2/emplexer/releases

**Comment by newloran2** [comment]
Avluis, you can please test with the new version of b03?

**Comment by avluis** [comment]
newloran2, downloaded file straight to the dune (via smb dune sharing to internal hdd), installed app from dune then went to settings and set my ip.
I have to say that this bad boy just works!

My Plex install on my Synology NAS has been much more stable as well (I have a lot of Hi10P media to convert) and Plex seems to be transcoding fine for most files.

Thank you!

**Comment by newloran2** [comment]
I'm glad it worked. 
One of the things that is on my list is an "advanced settings" to activate the transcoded session of PMS if the video meets certain conditions defined by the user. 
This will make it possible to see the videos in hi10p in Dune. 
I already use an alpha version of it in my test installation and i like it so much :).

**Comment by avluis** [comment]
I will be looking forward to that! And I offer myself and my videos as a guinea pig if you need them.
Unless you have all your test files in order, I've got a massive library that I would hate to spend time converting (in addition to additional manual scraping, due to the non-matching CRC from original release).

**Comment by newloran2** [comment]
I have several anime releases, and for me, Plex do a incredible work in scrapping that files.
I usually maintain that files with that struct: Anime name -> files with original name.
With it plex simple do the work for most of files.
But if you have problem try to use that meta data agent https://forums.plex.tv/index.php/topic/37750-anidb-metadata-agent/.

**Comment by avluis** [comment]
Yes, I use that plugin as well for Plex.
Only issue I seem to encounter most is when Plex does not distinguish S2 of an Anime Show that has some sort of change in its name or similar:

![screenshot 2014-03-23 08 13 24](https://f.cloud.github.com/assets/875593/2493318/49c388a4-b28d-11e3-9021-9f16928d53ff.png)
A 'very nice' show.
![screenshot 2014-03-23 08 13 43](https://f.cloud.github.com/assets/875593/2493319/49c3fbe0-b28d-11e3-9fc7-fbedafd61838.png)
How Plex sees it.
![screenshot 2014-03-23 08 15 28](https://f.cloud.github.com/assets/875593/2493320/49c448c0-b28d-11e3-973c-ebe67d384aac.png)
This is after anidb.net java scraper has run on that folder (how they want it)
![screenshot 2014-03-23 08 17 10](https://f.cloud.github.com/assets/875593/2493322/763cd93a-b28d-11e3-9e74-86bc4a871126.png)
This is season 2 of that show, no scraper ran yet.

**Comment by newloran2** [comment]
i forgot to say, split the files in season foldes.
I personaly use thetvdb to see the episode order http://thetvdb.com/?tab=series&id=172921&lid=7.
For example:
One Piece:
   s01:
      episodes
   s02:
      episodes
   Specials:
      episodes:

With that structure PMS can successfully scrap 95% of my collection.

**Comment by avluis** [comment]
Ah! Got it, I will have to do that in the future (my NAS auto-download and rename scripts need a bit of rework) as I implement a few automation tasks on my Syno.
Overall though, very happy with what I am getting so far!
