### ISSUE TITLE
Trouble starting V2 b03 - Unhandled PHP Plugin Error

### ISSUE THREAD

**Issue by keegesinn** [newloran2/emplexer#85]
Hello, 
The install of b03 went fine, and I put in the IP and port of the Plex Server. The whole thing works well on the same Dune HD Base 3D box with emplexer V1. But everytime I try to launch V2 b03, I get the "System error Unhandled PHP plugin error. Call the PHP plugin vendor". Log link is below, would be great if you could advise. 

Emplexer2 log at https://dl.dropboxusercontent.com/u/44716636/emplexer2.log

**Comment by newloran2** [comment]
Please keegesinn get the version available at releases https://github.com/newloran2/emplexer/releases
