### ISSUE TITLE
Seek to time and "resume from" seems does not work on 2.0-B03

### ISSUE THREAD

**Issue by pawel-smth** [newloran2/emplexer#88]
It's same copy as reported on https://forums.plex.tv/index.php/topic/33136-dune-player/page-41#entry738164

I need consultation on using Dune TV-303D as Plex "player". My software is as follows: emplexer 2.0-B03 on firmware 140610_0131_b8.

My use case is as follows: I browse Plex library on Android mobile app, and then start playback on Dune by selecting emplexer in "connect to" menu.

My two (related) questions does emplexer support (using Android mobile app):
1. seek to particular playback position while viewing video?
2. "resume from" feature?

Each time I try to seek to particular position (using Android mobile app) while video is playing, Android complains "Unable to connect to emplexer" and suggest to resume playback on mobile device instead of emplexter. Emplexer does not take any action and just continues playback.

Each time I try to "resume" playback from time I stopped previously, emplexer just starts playback from the beginning. Sometimes Android app complains that its "Unable to connect to emplexer".

Please advise.

**Comment by newloran2** [comment]
PavelGorbanj thanks for your report,

For now resume and seek with plex client are not supported.
I'll add this feature in next releases.

**Comment by pawel-smth** [comment]
I've closed it to clean up the list
