### ISSUE TITLE
 TV shows more  info

### ISSUE THREAD

**Issue by Blurayx** [newloran2/emplexer#9]
A bit more info for TV series please. 

While Watching TV shows, could you please add episode number and name, when info is pressed.

example:
![eg](https://f.cloud.github.com/assets/2873112/53144/c50b4946-5a4d-11e2-81a6-80fbc7e8c738.jpg)

**Comment by newloran2** [comment]
Done, in next installer commit emplexer have it.
![screenshot24](https://f.cloud.github.com/assets/1266496/53208/cf4f0190-5a52-11e2-8271-56e4ce531f2c.png)

**Comment by Blurayx** [comment]
Thanks!!
